[project]
name = "ai-gen"
version = "0.1.0"
description = "A Diary App with Flask and Vue3"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "flask>=2.0.0",
    "flask-cors>=3.0.10"
]
